config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  patch '/users/:id/edit_password' => 'users#edit_password', as: :edit_password

  get 'posts/hot' => 'posts#hot', as: :hot

  resources :posts, shallow: true do
    resources :comments, only: [:create, :destroy]
    resources :votes, only: [:create, :update, :destroy]
  end

  resources :users, except: [:destroy] do
    delete :destroy, on: :collection
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new

    can :manage, Post do |post|
      post.user == user
    end

    can :manage, Vote do |v|
      user == v.user
    end

    can :vote, Post do |v|
      user != v.user
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord

  mount_uploader :image, ImageUploader

  has_many :comments, {dependent: :destroy}
  has_many :votes, dependent: :destroy
  has_many :voters, through: :votes, source: :user

  belongs_to :user

  validates :title, presence: true
  validates :image, presence: true


  def vote_for(user)
    votes.find_by(user: user)
  end

  def votes_total
    votes.up.count - votes.down.count
  end

end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  has_many :posts, dependent: :nullify
  has_many :votes, dependent: :destroy
  has_many :voted_posts, through: :votes, source: :post
  has_many :comments, dependent: :destroy

  before_validation :downcase_email

  VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: VALID_EMAIL

  def full_name
    "#{first_name} #{last_name}".strip.titleize
  end

  private

  def downcase_email
    self.email&.downcase!
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :post_id, uniqueness: {scope: :user_id}

  def self.up
    where(is_up: true)
  end

  def self.down
    where(is_up: false)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  def authenticate_user!
    redirect_to new_session_path unless user_sign_in?
  end

  def user_sign_in?
    session[:user_id].present?
  end
  helper_method :user_sign_in?

  def current_user
    User.find session[:user_id] if user_sign_in?
  end
  helper_method :current_user

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end

  def create
    comment_params = params.require(:comment).permit(:body)
    @comment = Comment.new comment_params
    @comment.user = current_user
    @post = Post.find params[:post_id]
    @comment.post = @post
    if @comment.save
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def destroy
    @comment = Comment.find params[:id]
    @user = User.find @comment.user_id

    if current_user.id == @comment.user_id || current_user.is_admin == true
      @comment.destroy
      redirect_to post_path(@comment.post_id)
    else
      redirect_to post_path(@comment.post_id)
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.order(created_at: :desc)
  end

  def new
    @post = Post.new
    render :new, layout: false
  end

  def show
    @post = Post.find params[:id]
    @comment = Comment.new
    @vote = @post.vote_for(current_user)
  end

  def create
    @post = Post.new post_params
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path }
      else
        format.js { render :failure }
      end
    end
  end

  def hot
    @posts = Post.order(created_at: :desc)
  end

  private

  def post_params
    post_params = params.require(:post).permit(:title, :image)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new, layout: false
  end

  def create
    @user = User.find_by_email params[:email]
    respond_to do |format|
      if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        format.js { render :success}
      else
        format.js {render :failure}
      end
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :load_user, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    @user = User.new user_params
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.js {render :success}
      else
        format.js { render :failure }
      end
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path, notice: 'User updated!'
    else
      render :edit
    end
  end

  def edit_password
    if @user && @user.authenticate(params[:user][:current_password])
      if params[:user][:current_password] != params[:user][:new_password]
        if params[:user][:new_password] == params[:user][:new_password_confirmation]
          @user.password = params[:user][:new_password]
          @user.save
          redirect_to root_path, notice: "Password Updated!"
        else
          flash[:alert] = "new password must match the new password confirmation"
          render :edit
        end
      else
        flash[:alert] = "New password must be different from the current password"
      end
    else
      flash[:alert] = "Wrong password"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def load_user
    user = User.find_by_id params[:id]
    if current_user.id == user.id
      @user = user
    end
    @user
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  before_action :authenticate_user!
  before_action :find_post, only: :create
  before_action :vote_create, only: :create
  before_action :find_vote, :authorize_vote_change, only: [:update, :destroy]

  def create
    vote = Vote.new user: current_user, post: @post, is_up: params[:is_up]
    if vote.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def update
    if @vote.update is_up: params[:is_up]
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    if @vote.destroy
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def find_post
    @post = Post.find params[:post_id]
  end

  def find_vote
    @vote = Vote.find params[:id]
  end

  def vote_create
    redirect_to @post if cannot? :vote, @post
  end

  def authorize_vote_change
    if cannot? :manage, @vote
      redirect_to @vote.post
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><i class="fa fa-eercast" aria-hidden="true"></i></a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class='nav navbar-nav navbar-left'>
        <li><%= link_to 'Hot', hot_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_sign_in? %>
          <li><%= link_to 'Upload', new_post_path, data: {toggle: 'modal', target: '#upload'} %></li>
          <li><%= link_to current_user.full_name, edit_user_path(current_user), data: {toggle: 'modal', target: '#edit'} %></li>
          <li><%= link_to 'Logout', sessions_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign In', new_session_path, data: {toggle: 'modal', target: '#signin'} %></li>
          <li><%= link_to 'Sign Up', new_user_path, data: {toggle: 'modal', target: '#signup'} %></li>
        <% end %>
      </ul>

      <div class="modal fade" id="edit" tabindex="-1" role="dialog">
        <div class='modal-dialog'>
          <div class='modal-content' style='padding: 0px 20px 20px 20px'>

          </div>
        </div>
      </div>

      <div class="modal fade" id="signin" tabindex="-1" role="dialog">
        <div class='modal-dialog'>
          <div class='modal-content' style='padding: 0px 20px 20px 20px'>

          </div>
        </div>
      </div>

      <div class="modal fade" id="signup" tabindex="-1" role="dialog">
        <div class='modal-dialog'>
          <div class='modal-content' style='padding: 0px 20px 20px 20px'>

          </div>
        </div>
      </div>

      <div class="modal fade" id="upload" tabindex="-1" role="dialog">
        <div class='modal-dialog'>
          <div class='modal-content' style='padding: 0px 20px 20px 20px'>

          </div>
        </div>
      </div>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WTF</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/failure.js.erb
$('#error-msg').remove();
$('#error').append("<p id='error-msg' style='color:red'>Failed to upload, please try again</p>");

app/views/posts/hot.html.erb
<%= render partial: 'layouts/navbar' %>
<br><br><br><br>

<div class='text-center'>
  <div class='container-fluid'>
    <div class='row'>

      <% @posts.each do |p| %>
        <% if p.votes_total > 20 %>
          <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12' style='padding:0px'>
            <h4><%= link_to p.title, post_path(p) %></h4>
            <%= link_to image_tag(p.image), post_path(p) %>
            <br>
            <span style='padding-right:14.5em'><%= p.votes_total%> points • <%= p.comments.count %> comments</span>
            <br>
            <div style='padding-right:18.5em'>
              <% if p.vote_for(current_user).nil? %>
                <%= link_to post_votes_path(p, { is_up: true }), method: :post do %>
                  <i class="fa fa-arrow-circle-up fa-2x" aria-hidden="true"></i>
                <% end %>
                <%= link_to post_votes_path(p, { is_up: false }), method: :post do %>
                  <i class="fa fa-arrow-circle-down fa-2x" aria-hidden="true"></i>
                <% end %>
              <% elsif p.vote_for(current_user).is_up? %>
                <%= link_to vote_path(p.vote_for(current_user)), method: :delete do %>
                  <i class="fa fa-arrow-circle-up fa-2x" aria-hidden="true"></i>
                <% end %>
                <%= link_to vote_path(p.vote_for(current_user), { is_up: false }), method: :patch do %>
                  <i class="fa fa-arrow-circle-down fa-2x" aria-hidden="true"></i>
                <% end %>
              <% else %>
                <%= link_to vote_path(p.vote_for(current_user), { is_up: true }), method: :patch do %>
                  <i class="fa fa-arrow-circle-up fa-2x" aria-hidden="true"></i>
                <% end %>
                <%= link_to vote_path(p.vote_for(current_user)), method: :delete do %>
                  <i class="fa fa-arrow-circle-down fa-2x" aria-hidden="true"></i>
                <% end %>
              <% end %>
              <%= link_to post_path(p) do %>
                <i class="fa fa-commenting-o fa-2x" aria-hidden="true"></i>
              <% end %>
            </div>
            <hr style='width:27em'>
          </div>
        <% end %>
      <% end %>

    </div>
  </div>
</div>

app/views/posts/index.html.erb
<%= render partial: 'layouts/navbar' %>
<br><br><br><br>
<div class='text-center'>
  <div class='container-fluid'>
    <div class='row'>

      <% @posts.each do |p| %>
        <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12' style='padding:0px'>
          <h4><%= link_to p.title, post_path(p) %></h4>
          <%= link_to image_tag(p.image), post_path(p) %>
          <br>
          <span id='votes_total'><%= p.votes_total %> points</span>
          <span id='comment_total' style='padding-right:14em'>• <%= p.comments.count %> comments</span>

          <br>

          <div style='padding-right:18.5em'>
            <% if p.vote_for(current_user).nil? %>
              <%= link_to post_votes_path(p, { is_up: true }), method: :post do %>
                <i class="fa fa-arrow-circle-up fa-2x" aria-hidden="true"></i>
              <% end %>
              <%= link_to post_votes_path(p, { is_up: false }), method: :post do %>
                <i class="fa fa-arrow-circle-down fa-2x" aria-hidden="true"></i>
              <% end %>
            <% elsif p.vote_for(current_user).is_up? %>
              <%= link_to vote_path(p.vote_for(current_user)), method: :delete do %>
                <i class="fa fa-arrow-circle-up fa-2x" aria-hidden="true"></i>
              <% end %>
              <%= link_to vote_path(p.vote_for(current_user), { is_up: false }), method: :patch do %>
                <i class="fa fa-arrow-circle-down fa-2x" aria-hidden="true"></i>
              <% end %>
            <% else %>
              <%= link_to vote_path(p.vote_for(current_user), { is_up: true }), method: :patch do %>
                <i class="fa fa-arrow-circle-up fa-2x" aria-hidden="true"></i>
              <% end %>
              <%= link_to vote_path(p.vote_for(current_user)), method: :delete do %>
                <i class="fa fa-arrow-circle-down fa-2x" aria-hidden="true"></i>
              <% end %>
            <% end %>
            <%= link_to post_path(p) do %>
              <i class="fa fa-commenting-o fa-2x" aria-hidden="true"></i>
            <% end %>
          </div>
          <hr style='width:27em'>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/posts/new.html.erb
<h1>Create A New Post
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</h1>

<div id='error'></div>
<%= simple_form_for @post, remote: true do |f| %>
<%= f.input :title %>
<%= f.input :image %>
<%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/posts/show.html.erb
<%= render partial: 'layouts/navbar' %>
<br><br><br><br>

<div class='text-center'>
  <h3><%= @post.title %></h3>
  <%= image_tag(@post.image) %>
  <br>
  <span style='padding-right:14.5em'><%= @post.votes_total %> points • <%= @post.comments.count %> comments</span>
  <div style='padding-right:21em'>

    <% if @vote.nil? %>
      <%= link_to post_votes_path(@post, { is_up: true }), method: :post do %>
        <i class="fa fa-arrow-circle-up fa-2x" aria-hidden="true"></i>
      <% end %>
      <%= link_to post_votes_path(@post, { is_up: false }), method: :post do %>
        <i class="fa fa-arrow-circle-down fa-2x" aria-hidden="true"></i>
      <% end %>
    <% elsif @vote.is_up? %>
      <%= link_to vote_path(@post.vote_for(current_user)), method: :delete do %>
        <i class="fa fa-arrow-circle-up fa-2x" aria-hidden="true"></i>
      <% end %>
      <%= link_to vote_path(@post.vote_for(current_user), { is_up: false }), method: :patch do %>
        <i class="fa fa-arrow-circle-down fa-2x" aria-hidden="true"></i>
      <% end %>
    <% else %>
      <%= link_to vote_path(@post.vote_for(current_user), { is_up: true }), method: :patch do %>
        <i class="fa fa-arrow-circle-up fa-2x" aria-hidden="true"></i>
      <% end %>
      <%= link_to vote_path(@post.vote_for(current_user)), method: :delete do %>
        <i class="fa fa-arrow-circle-down fa-2x" aria-hidden="true"></i>
      <% end %>
    <% end %>

  </div>
  <hr>

  <% if user_sign_in? %>
    <%= simple_form_for [@post, @comment] do |c| %>
      <div>
        <h4><%= current_user.full_name %></h4>
        <%= c.text_area :body, cols: "40", rows: "3", placeholder: 'Leave a Comment' %>
        <br>
      </div>
      <div style='padding-left:19.5em'>
        <%= c.submit 'Post', class: 'btn btn-primary btn-sm' %>
      </div>
      <hr>
    <% end %>
  <% end %>

  <div>
    <% @post.comments.order(created_at: :asc).each do |c| %>
    <%= c.user.full_name %>:
    <%= c.body %>
    <div class='pull-right'>
      <%= link_to 'Delete', comment_path(c), method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    <br><br>
    <% end %>
  </div>
  <br><br>
</div>

app/views/posts/success.js.erb
window.location.reload();

app/views/users/edit.html.erb
<div style='margin-bottom: 20px'>
  <h1>Edit Profile
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </h1>

  <%= simple_form_for @user do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email, required: false %>
  <%= f.submit 'Update Profile', class: 'btn btn-primary' %>
  <% end %>

  <h1>Update Password</h1>

  <%= simple_form_for @user, :url => edit_password_path(@user) do |f| %>
  <%= f.input :current_password %>
  <%= f.input :new_password %>
  <%= f.input :new_password_confirmation %>
  <%= f.submit 'Update Password', class: 'btn btn-primary' %>
  <% end %>

  <h1>Delete Account</h1>
  <%= link_to "Delete", user_path(@user), method: :delete, class: 'btn btn-danger' %>

</div>

app/views/users/failure.js.erb
$('#error-msg').remove();
$('#error').append("<p id='error-msg' style='color:red'>Failed to sign up, please try again</p>");

app/views/users/new.html.erb
<h1>Sign Up
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</h1>
<div id='error'></div>
<%= simple_form_for @user, remote:true do |f| %>
<%= f.input :first_name %>
<%= f.input :last_name %>
<%= f.input :email %>
<%= f.input :password %>
<%= f.input :password_confirmation %>
<%= f.submit 'Sign Up', class: 'btn btn-primary' %>
<% end %>